on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dzbuild.azurecr.io
        username: ${{ secrets.acr_dzbuild_username }}
        password: ${{ secrets.acr_dzbuild_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t dzbuild.azurecr.io/demo1:${{ github.sha }}
        docker push dzbuild.azurecr.io/demo1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demo1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo1bf22 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo1bf22`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo1bf22
        container-registry-url: dzbuild.azurecr.io
        container-registry-username: ${{ secrets.acr_dzbuild_username }}
        container-registry-password: ${{ secrets.acr_dzbuild_password }}
        secret-name: demo1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: demo1bf22
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          dzbuild.azurecr.io/demo1:${{ github.sha }}
        imagepullsecrets: |
          demo1dockerauth